// api/hrms/availabilityApi.ts
// Availability Calendar API

import { apiClient as client } from '../client';

// Types
export interface EmployeeAvailability {
  id: string;
  tenantId: string;
  employeeId: string;
  date: string;
  startDate?: string;
  endDate?: string;
  status: 'AVAILABLE' | 'UNAVAILABLE' | 'BLOCKED' | 'ON_LEAVE' | 'ON_TRIP' | 'TENTATIVE';
  blockReason?: 'PERSONAL' | 'TRAINING' | 'MEDICAL' | 'OTHER';
  notes?: string;
  isAutoGenerated: boolean;
  sourceType?: 'LEAVE' | 'TRIP' | 'SCHEDULE' | 'MANUAL';
  sourceId?: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface CalendarEntry {
  date: string;
  employeeId: string;
  employeeName: string;
  status: string;
  reason?: string;
  tripName?: string;
  leaveType?: string;
}

export interface TeamSummary {
  date: string;
  totalStaff: number;
  available: number;
  onTrip: number;
  onLeave: number;
  unavailable: number;
}

export interface AvailableStaff {
  employeeId: string;
  employeeName: string;
  category: string;
  skills: string[];
}

export interface CreateAvailabilityDTO {
  employeeId: string;
  date: string;
  startDate?: string;
  endDate?: string;
  status: 'AVAILABLE' | 'UNAVAILABLE' | 'BLOCKED' | 'ON_LEAVE' | 'ON_TRIP' | 'TENTATIVE';
  blockReason?: 'PERSONAL' | 'TRAINING' | 'MEDICAL' | 'OTHER';
  notes?: string;
}

export interface BulkAvailabilityDTO {
  employeeId: string;
  dates: string[];
  status: 'AVAILABLE' | 'UNAVAILABLE' | 'BLOCKED' | 'ON_LEAVE' | 'ON_TRIP' | 'TENTATIVE';
  blockReason?: 'PERSONAL' | 'TRAINING' | 'MEDICAL' | 'OTHER';
  notes?: string;
}

export interface CalendarQuery {
  startDate: string;
  endDate: string;
  employeeIds?: string[];
  branchId?: string;
}

export interface AvailableStaffQuery {
  startDate: string;
  endDate: string;
  branchId?: string;
  category?: string;
  excludeEmployeeIds?: string[];
}

// API Functions
export const availabilityApi = {
  // Get calendar entries
  getCalendarEntries: async (query: CalendarQuery): Promise<CalendarEntry[]> => {
    const params = new URLSearchParams({
      startDate: query.startDate,
      endDate: query.endDate,
    });
    if (query.employeeIds?.length) params.set('employeeIds', query.employeeIds.join(','));
    if (query.branchId) params.set('branchId', query.branchId);

    const response = await client.get(`/hrms/availability/calendar?${params}`);
    return response.data.data;
  },

  // Get team summary
  getTeamSummary: async (query: CalendarQuery): Promise<TeamSummary[]> => {
    const params = new URLSearchParams({
      startDate: query.startDate,
      endDate: query.endDate,
    });
    if (query.branchId) params.set('branchId', query.branchId);

    const response = await client.get(`/hrms/availability/team-summary?${params}`);
    return response.data.data;
  },

  // Get available staff
  getAvailableStaff: async (query: AvailableStaffQuery): Promise<AvailableStaff[]> => {
    const params = new URLSearchParams({
      startDate: query.startDate,
      endDate: query.endDate,
    });
    if (query.branchId) params.set('branchId', query.branchId);
    if (query.category) params.set('category', query.category);
    if (query.excludeEmployeeIds?.length) params.set('excludeEmployeeIds', query.excludeEmployeeIds.join(','));

    const response = await client.get(`/hrms/availability/available-staff?${params}`);
    return response.data.data;
  },

  // Get employee availability
  getByEmployee: async (employeeId: string, startDate: string, endDate: string): Promise<EmployeeAvailability[]> => {
    const params = new URLSearchParams({ startDate, endDate });
    const response = await client.get(`/hrms/availability/employee/${employeeId}?${params}`);
    return response.data.data;
  },

  // Check conflicts
  checkConflicts: async (employeeId: string, startDate: string, endDate: string, excludeId?: string): Promise<boolean> => {
    const params = new URLSearchParams({ startDate, endDate });
    if (excludeId) params.set('excludeId', excludeId);
    const response = await client.get(`/hrms/availability/employee/${employeeId}/conflicts?${params}`);
    return response.data.data.hasConflicts;
  },

  // CRUD operations
  getById: async (id: string): Promise<EmployeeAvailability> => {
    const response = await client.get(`/hrms/availability/${id}`);
    return response.data.data;
  },

  create: async (data: CreateAvailabilityDTO): Promise<EmployeeAvailability> => {
    const response = await client.post('/hrms/availability', data);
    return response.data.data;
  },

  createBulk: async (data: BulkAvailabilityDTO): Promise<EmployeeAvailability[]> => {
    const response = await client.post('/hrms/availability/bulk', data);
    return response.data.data;
  },

  update: async (id: string, data: Partial<CreateAvailabilityDTO>): Promise<EmployeeAvailability> => {
    const response = await client.put(`/hrms/availability/${id}`, data);
    return response.data.data;
  },

  delete: async (id: string): Promise<void> => {
    await client.delete(`/hrms/availability/${id}`);
  },
};
