// application/dtos/hrms/AvailabilityDTO.ts
// Availability DTOs and Mappers

import type { 
  EmployeeAvailability, 
  AvailabilityCalendarEntry,
  TeamAvailabilitySummary 
} from '../../../domain/entities/hrms/Availability';

// Request DTOs
export interface CreateAvailabilityDTO {
  employeeId: string;
  date: string;
  startDate?: string;
  endDate?: string;
  status: 'AVAILABLE' | 'UNAVAILABLE' | 'BLOCKED' | 'ON_LEAVE' | 'ON_TRIP' | 'TENTATIVE';
  blockReason?: 'PERSONAL' | 'TRAINING' | 'MEDICAL' | 'OTHER';
  notes?: string;
}

export interface UpdateAvailabilityDTO {
  status?: 'AVAILABLE' | 'UNAVAILABLE' | 'BLOCKED' | 'ON_LEAVE' | 'ON_TRIP' | 'TENTATIVE';
  blockReason?: 'PERSONAL' | 'TRAINING' | 'MEDICAL' | 'OTHER';
  notes?: string;
}

export interface BulkAvailabilityDTO {
  employeeId: string;
  dates: string[];
  status: 'AVAILABLE' | 'UNAVAILABLE' | 'BLOCKED' | 'ON_LEAVE' | 'ON_TRIP' | 'TENTATIVE';
  blockReason?: 'PERSONAL' | 'TRAINING' | 'MEDICAL' | 'OTHER';
  notes?: string;
}

export interface CalendarQueryDTO {
  startDate: string;
  endDate: string;
  employeeIds?: string[];
  branchId?: string;
}

export interface AvailableStaffQueryDTO {
  startDate: string;
  endDate: string;
  branchId?: string;
  category?: string;
  excludeEmployeeIds?: string[];
}

// Response DTOs
export interface AvailabilityResponseDTO {
  id: string;
  tenantId: string;
  employeeId: string;
  date: string;
  startDate?: string;
  endDate?: string;
  status: string;
  blockReason?: string;
  notes?: string;
  isAutoGenerated: boolean;
  sourceType?: string;
  sourceId?: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
}

export interface CalendarEntryResponseDTO {
  date: string;
  employeeId: string;
  employeeName: string;
  status: string;
  reason?: string;
  tripName?: string;
  leaveType?: string;
}

export interface TeamSummaryResponseDTO {
  date: string;
  totalStaff: number;
  available: number;
  onTrip: number;
  onLeave: number;
  unavailable: number;
}

export interface AvailableStaffResponseDTO {
  employeeId: string;
  employeeName: string;
  category: string;
  skills: string[];
}

// Mappers
export const AvailabilityMapper = {
  toResponseDTO(entity: EmployeeAvailability): AvailabilityResponseDTO {
    return {
      id: entity.id,
      tenantId: entity.tenantId,
      employeeId: entity.employeeId,
      date: entity.date.toISOString().split('T')[0],
      startDate: entity.startDate?.toISOString().split('T')[0],
      endDate: entity.endDate?.toISOString().split('T')[0],
      status: entity.status,
      blockReason: entity.blockReason,
      notes: entity.notes,
      isAutoGenerated: entity.isAutoGenerated,
      sourceType: entity.sourceType,
      sourceId: entity.sourceId,
      createdAt: entity.createdAt.toISOString(),
      updatedAt: entity.updatedAt.toISOString(),
      createdBy: entity.createdBy,
    };
  },

  toCalendarEntryDTO(entry: AvailabilityCalendarEntry): CalendarEntryResponseDTO {
    return {
      date: entry.date,
      employeeId: entry.employeeId,
      employeeName: entry.employeeName,
      status: entry.status,
      reason: entry.reason,
      tripName: entry.tripName,
      leaveType: entry.leaveType,
    };
  },

  toTeamSummaryDTO(summary: TeamAvailabilitySummary): TeamSummaryResponseDTO {
    return {
      date: summary.date,
      totalStaff: summary.totalStaff,
      available: summary.available,
      onTrip: summary.onTrip,
      onLeave: summary.onLeave,
      unavailable: summary.unavailable,
    };
  },
};
