// domain/entities/hrms/Availability.ts
// Employee availability tracking for scheduling

export type AvailabilityStatus = 
  | 'AVAILABLE' 
  | 'UNAVAILABLE' 
  | 'TENTATIVE'
  | 'ON_TRIP'
  | 'ON_LEAVE'
  | 'BLOCKED';

export type BlockReason = 
  | 'PERSONAL'
  | 'MEDICAL'
  | 'TRAINING'
  | 'TRAVEL'
  | 'OTHER';

export interface EmployeeAvailability {
  id: string;
  tenantId: string;
  employeeId: string;
  
  // Date range
  date: Date;           // For single day entries
  startDate?: Date;     // For range entries
  endDate?: Date;
  
  // Status
  status: AvailabilityStatus;
  blockReason?: BlockReason;
  notes?: string;
  
  // Auto-generated from system
  isAutoGenerated: boolean;  // From trips, leaves, etc.
  sourceType?: 'TRIP' | 'LEAVE' | 'SCHEDULE' | 'MANUAL';
  sourceId?: string;
  
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
}

export interface AvailabilityCalendarEntry {
  date: string;
  employeeId: string;
  employeeName: string;
  status: AvailabilityStatus;
  reason?: string;
  tripName?: string;
  leaveType?: string;
}

export interface TeamAvailabilitySummary {
  date: string;
  totalStaff: number;
  available: number;
  onTrip: number;
  onLeave: number;
  unavailable: number;
}

export interface AvailableStaffQuery {
  tenantId: string;
  startDate: Date;
  endDate: Date;
  skills?: string[];
  category?: string;
  branchId?: string;
  excludeEmployeeIds?: string[];
}

export function createAvailability(
  params: Omit<EmployeeAvailability, 'id' | 'createdAt' | 'updatedAt'>
): Omit<EmployeeAvailability, 'id'> {
  return {
    ...params,
    createdAt: new Date(),
    updatedAt: new Date(),
  };
}

export function isAvailable(entry: EmployeeAvailability): boolean {
  return entry.status === 'AVAILABLE' || entry.status === 'TENTATIVE';
}
